# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
  - id: go-fmt
  - id: go-imports
  - id: no-go-testing
  - id: golangci-lint
  - id: go-unit-tests
    # - id: validate-toml
- repo: https://github.com/golangci/golangci-lint   # golangci-lint hook repo
  rev: v1.50.1   # golangci-lint hook repo revision
  hooks:
  - id: golangci-lint     # hook id
